### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by zlokomatic** [fretsonfire/core#1]
Topic says it all: Is this project still alive? :)

**Comment by xaoseric** [comment]
yes it is, just working on the c++ code for the frets on fire engine

**Comment by zlokomatic** [comment]
Any updates on this? :D

**Comment by xaoseric** [comment]
I will be uploading the source code later today, hopefully this after noon. We are using QT5 for the development of it.

**Comment by zlokomatic** [comment]
? :D

**Comment by xaoseric** [comment]
yes, the project is still alive, I have been busy lately, apologies for the lateness.

**Comment by markwdickson** [comment]
Apologies for the lateness?  Dude, it's been 3 years since you said "will be uploading later today."  I understand spare-time projects being put on hold, but just admit the reality.  The first question as to whether this project is still active or not was asked nearly 5 years ago without even a single, partial code commit since then.  I think THAT truly answers the OPs question.
